spring:
  datasource:
    url: jdbc:mysql://localhost:3306/masspp
    username: root
    password: J_yhmm/197844
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
logging:
  level:
    com:
      john:
        masspp: DEBUG
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
  path: logs
